script:
  - id: canopy_green_chase
    mode: restart
    then:
      - light.turn_on:
          id: canopy_lights
          effect: "Startup Chase"
      - light.turn_on:
          id: base_lights
          effect: "Startup Chase"
      - delay: 10s
      - light.turn_off: canopy_lights
      - light.turn_off: base_lights
  - id: warning_chase
    mode: restart
    then:
      - light.turn_on:
          id: canopy_lights
          effect: "Warning Chase"
      - light.turn_on:
          id: base_lights
          effect: "Warning Chase"
  - id: testing_chase
    mode: restart
    then:
      - light.turn_on:
          id: canopy_lights
          effect: "Testing Chase"
      - light.turn_on:
          id: base_lights
          effect: "Testing Chase"
  - id: stop_addressable_effects
    mode: restart
    then:
      - light.turn_off: canopy_lights
      - light.turn_off: base_lights
