- platform: hdc1080
  update_interval: 30s
  temperature:
    name: "Chamber Temperature °C"
    id: chamber_temperature_c
    unit_of_measurement: "°C"
    accuracy_decimals: 1
  humidity:
    name: "Chamber Humidity"
    id: chamber_humidity
    unit_of_measurement: "%"
    accuracy_decimals: 1

- platform: template
  name: "Chamber Temperature"
  id: chamber_temperature
  unit_of_measurement: "°F"
  accuracy_decimals: 1
  lambda: |-
    if (isnan(id(chamber_temperature_c).state)) {
      return NAN;
    }
    return id(chamber_temperature_c).state * 9.0f / 5.0f + 32.0f;
