# Temperature and Humidity Sensors

sensor:
  # HDC1080 I2C sensor
  - platform: hdc1080
    update_interval: 30s
    temperature:
      name: "${friendly_name} Temperature Celsius"
      id: chamber_temperature_celsius
      unit_of_measurement: "°C"
      accuracy_decimals: 1
    humidity:
      name: "${friendly_name} Humidity"
      id: chamber_humidity
      unit_of_measurement: "%"
      accuracy_decimals: 1

  # Fahrenheit conversion
  - platform: template
    name: "${friendly_name} Temperature"
    id: chamber_temperature
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    lambda: |-
      if (isnan(id(chamber_temperature_celsius).state)) {
        return NAN;
      }
      return id(chamber_temperature_celsius).state * 9.0f / 5.0f + 32.0f;
